name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: install frontend dependencies
        run: pnpm install # change this to npm, pnpm or bun depending on which one you use.
      - name: Install dependencies
        run: pnpm install # change this to npm, pnpm or bun depending on which one you use.
      - name: Build NestJS Project
        run: pnpm run build
      - name: Build Project Artifacts
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
